In [3]:
import pandas as pd
from mlxtend .preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [6]:
items_list=[['bread','butter','jam','milk'],
            ["bread","butter","milk"],
            ["bread","juice","curd"],
            ["bread","milk","juice"],
            ["butter","milk","juice"]]
items_list

[['bread', 'butter', 'jam', 'milk'],
 ['bread', 'butter', 'milk'],
 ['bread', 'juice', 'curd'],
 ['bread', 'milk', 'juice'],
 ['butter', 'milk', 'juice']]

In [8]:
encode=TransactionEncoder()
data=encode.fit(items_list).transform(items_list)
df=pd.DataFrame(data,columns=encode.columns_)
df

   bread  butter   curd    jam  juice   milk
0   True    True  False   True  False   True
1   True    True  False  False  False   True
2   True   False   True  False   True  False
3   True   False  False  False   True   True
4  False    True  False  False   True   True

In [11]:
item_set=apriori(df,min_support=0.5,use_colnames=True)
item_set

   support        itemsets
0      0.8         (bread)
1      0.6        (butter)
2      0.6         (juice)
3      0.8          (milk)
4      0.6   (milk, bread)
5      0.6  (butter, milk)

In [15]:
rules=association_rules(item_set,metric="confidence",min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(milk),(bread),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
1,(bread),(milk),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
2,(butter),(milk),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
3,(milk),(butter),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875

In [18]:
x=rules.iloc[:,[0,1,3,4]]
x

  antecedents consequents  consequent support  support
0      (milk)     (bread)                 0.8      0.6
1     (bread)      (milk)                 0.8      0.6
2    (butter)      (milk)                 0.8      0.6
3      (milk)    (butter)                 0.6      0.6